### ISSUE TITLE
Fatal error: Can't use method return value in write context in class-paymentwall-gateway.php on line 52

### ISSUE THREAD

**Issue by MyNameIsAlaa** [paymentwall/module-woocommerce#14]
hello,

i have woocommerce site and after installing the plugin i got the following error:

 Fatal error: Can't use method return value in write context in /home4/selim/public_html/xxxxx.com/wp-content/plugins/paymentwall-for-woocommerce/includes/class-paymentwall-gateway.php on line 52

any idea how to fix this?
thanks

**Comment by michaelpw** [comment]
Hello,

It looks like our module on your server is missing the Paymentwall library. Could you download the latest release of our module for Woocommerce in the following link?

https://github.com/paymentwall/module-woocommerce/releases

Let me know if the error persists.
Thanks

**Comment by MyNameIsAlaa** [comment]
@michaelpw I have downloaded paymentwall-module-woocommerce-v1-5-4.zip and upload it to my server and when i try to activate the plugin i got the same error:

Fatal error: Can't use method return value in write context in /home4/selim/public_html/domain.com/wp-content/plugins/paymentwall-for-woocommerce/includes/class-paymentwall-gateway.php on line 52

**Comment by michaelpw** [comment]
Hi @00Alaa00 ,

Could you send me through email the Admin access and FTP access to Paymentwall files on your server and we will investigate to fix this issue? My email address is **michael.nguyen@paymentwall.com**
Thanks.

**Comment by hdolinski** [comment]
empty() results error if not used directly on a variable in PHP < 5.5. This
is fixable by assigning the return value of the method inside empty() to a
variable, and then check the variable with empty()

**Comment by MyNameIsAlaa** [comment]
@hdolinski thanks, hopefully someone would update the plugin and fix this issue, i have many other websites on the server and i'm afraid upgrading php version may break something.

**Comment by michaelpw** [comment]
@hdolinski thanks for the suggestion
@00Alaa00 we have been aware of this issue and working on the update to fix. It's going to be released soon. We will keep you updated

**Comment by michaelpw** [comment]
@00Alaa00 Our revised version to fix the compatibility issue has been released. You can download it in the following link:
https://github.com/paymentwall/module-woocommerce/releases/tag/v1.5.5

If you found any other issues, feel free to contact me via email **michael@paymentwall.com**

**Comment by MyNameIsAlaa** [comment]
@michaelpw thanks it works perfectly now :)
